name: Deploy React App to EC2

on:
  push:
    branches: [ master ]  # Trigger deployment on push to main branch
  workflow_dispatch:    # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        env:
          CI: false  # Prevents build from failing on warnings
      
      # Generate a timestamp file to verify deployment
      - name: Create deployment timestamp
        run: echo "Deployment timestamp: $(date)" > build/deployment_timestamp.txt
      
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.EC2_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host ec2\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh/deploy_key\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      
      - name: Deploy to EC2
        run: |
          # Create a tar archive of the build folder
          tar -czf deploy.tar.gz -C build .
          
          # Copy to EC2
          scp -o StrictHostKeyChecking=no deploy.tar.gz ec2:~/
          
          # Deploy commands via SSH
          ssh ec2 << 'EOL'
            # Set deployment directory (adjust as needed)
            DEPLOY_DIR=/var/www/html
            
            # Debug information
            echo "Starting deployment process..."
            echo "Current directory content before deployment:"
            ls -la $DEPLOY_DIR
            
            # Backup current deployment (optional)
            if [ -d "$DEPLOY_DIR" ]; then
              BACKUP_DIR=$DEPLOY_DIR.backup-$(date +%Y%m%d%H%M%S)
              sudo cp -r $DEPLOY_DIR $BACKUP_DIR
              echo "Backup created at $BACKUP_DIR"
            fi
            
            # Extract new deployment
            mkdir -p ~/deployment
            tar -xzf ~/deploy.tar.gz -C ~/deployment
            echo "Files extracted to temporary directory"
            ls -la ~/deployment
            
            # Move to web directory (may require sudo)
            echo "Removing old files and copying new ones..."
            sudo rm -rf $DEPLOY_DIR/*
            sudo cp -r ~/deployment/* $DEPLOY_DIR/
            
            # Fix permissions
            sudo chown -R www-data:www-data $DEPLOY_DIR
            
            # Clear Nginx cache if exists
            sudo rm -rf /var/cache/nginx/* 2>/dev/null || true
            
            # Restart Nginx
            sudo systemctl restart nginx
            echo "Nginx restarted"
            
            # Verify deployment
            echo "New directory content after deployment:"
            ls -la $DEPLOY_DIR
            
            # Check for timestamp file to verify deployment
            if [ -f "$DEPLOY_DIR/deployment_timestamp.txt" ]; then
              echo "Deployment verification:"
              cat $DEPLOY_DIR/deployment_timestamp.txt
            else
              echo "WARNING: Timestamp file not found. Deployment may have issues."
            fi
            
            # Clean up
            rm ~/deploy.tar.gz
            rm -rf ~/deployment
            echo "Deployment complete!"
          EOL
